baseURL = 'https://802-1x.github.io/ncsg-presentation-august-2024/#/'
languageCode = 'en-au'
title = 'ncsg-presentation-august-2024'
theme = ["reveal-hugo"]

[outputFormats.Reveal]
baseName = "index"
mediaTyype = "text.html"
isHTML = true

[params.reveal_hugo]
hideInactiveCursor = true
highlight_theme = "tomorrow-night-blue"
history = true
slide_number = true
theme = "blood"
transition_speed = "fast"

[markup.highlight]
codeFences = false

[markup.goldmark.extensions.extra.superscript]
enable = true
